version: 1

update_configs:
  - package_manager: "go:modules"
    directory: "/services/bondster-bco-rest"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/services/bondster-bco-unit"
    update_schedule: "daily"
