.nh
.TH "BONDSTER-BCO-REST" "1" "Jul 2020" "Bondster Marketplace Manager" "OpenBank Bondster Marketplace Manager REST Server Manual"
.sp
.SH "NAME"
lake \- starts openbank bondster marketplace connector REST server
.SH "SYNOPSIS"
.sp
.nf
\fIbondster-bco-rest
.fi
.sp
.SH "DESCRIPTION"
.sp
The bondster bco rest provides REST server for accessing and manipulating bondster bco units
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
