.nh
.TH "BONDSTER-BCO-IMPORT" "1" "Jul 2020" "Bondster Marketplace Import" "OpenBank Bondster Marketplace Import Manual"
.sp
.SH "NAME"
lake \- starts openbank bondster marketplace connector import unit
.SH "SYNOPSIS"
.sp
.nf
\fIbondster-bco-import
.fi
.sp
.SH "DESCRIPTION"
.sp
The bondster bco import manages tenant bondster tokens and imports transactions from bondster marketplace
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
